// Verifies a deployed copy of the site actually serves before it is allowed
// to be promoted. Runs against the staged URL, not the repository, so it
// catches what a file-level check cannot: a publish that uploaded nothing, a
// wrong publish directory, a redirect rule that swallows every path.
//
//   node tools/smoke-check.mjs https://staging--example.netlify.app
import { argv, exit } from 'node:process';

const base = (argv[2] || '').replace(/\/+$/, '');
if (!base) { console.error('usage: node tools/smoke-check.mjs <base-url>'); exit(2); }

// One representative of every page shape the site serves.
const PAGES = [
  { path: '/',              must: ['VAAV', '</html>'] },
  { path: '/menu/',         must: ['Tiffin', 'Lunch', 'Dinner'] },
  { path: '/menu/tiffin/',  must: ['GENERATED by tools/build-menu-pages.mjs'] },
  { path: '/about/',        must: ['</html>'] },
  { path: '/contact/',      must: ['</html>'] },
  { path: '/services/',     must: ['</html>'] },
  { path: '/corporate/',    must: ['</html>'] },
  { path: '/robots.txt',    must: ['Sitemap'] },
  { path: '/sitemap.xml',   must: ['<urlset'] },
];

const problems = [];

for (const { path, must } of PAGES) {
  const url = base + path;
  let res, body;
  try {
    res = await fetch(url, { redirect: 'follow' });
    body = await res.text();
  } catch (err) {
    problems.push(`${path} -- request failed: ${err.message}`);
    continue;
  }
  if (res.status !== 200) { problems.push(`${path} -- HTTP ${res.status}`); continue; }
  for (const needle of must) {
    if (!body.includes(needle)) problems.push(`${path} -- served 200 but is missing ${JSON.stringify(needle)}`);
  }
}

// A page that does not exist must 404, not serve the homepage. A catch-all
// that answers everything with 200 is the failure this catches.
try {
  const res = await fetch(base + '/definitely-not-a-real-page-' + Date.now(), { redirect: 'follow' });
  if (res.status !== 404) problems.push(`unknown paths return HTTP ${res.status}, expected 404`);
} catch (err) {
  problems.push(`404 probe failed: ${err.message}`);
}

if (problems.length) {
  for (const p of problems) console.error(`::error::${p}`);
  console.error(`${problems.length} problem(s) against ${base}`);
  exit(1);
}
console.log(`OK: ${PAGES.length} pages served, unknown paths 404 (${base})`);
