#!/usr/bin/env node
// Syncs the shared topbar + nav block into the hand-maintained pages.
//
//   npm run sync:chrome       (from site/)
//
// The block was 3.7 KB duplicated by hand across seven pages, so a nav change
// meant seven identical edits and any missed one drifted silently. It now has
// one home, tools/chrome/nav.html, and this tool rewrites the marked region
// inside each page from it.
//
// This is deliberately NOT a static site generator. The pages stay whole,
// hand-editable HTML files under version control; only the region between the
// markers is machine-owned. There is no layout file, no content extraction and
// no page-source directory, and there never should be: the output is committed
// like any other source file, because netlify.toml publishes site/ exactly as
// it stands and nothing is built at deploy time. See ADR-0004.
//
// Lives outside site/ deliberately -- site/ is the Netlify publish directory,
// so anything in it is served publicly. See ADR-0005.
//
// ORDERING: run this BEFORE `npm run build:menu`. The generated category pages
// copy their chrome verbatim out of site/menu/index.html, so building them from
// an unsynced hub bakes stale chrome into all three. `npm run build:menu`
// chains this script ahead of itself so the order cannot be got wrong by hand.

import { readFileSync, writeFileSync } from 'node:fs';

const SITE = new URL('../site/', import.meta.url);
const NAV_SOURCE = new URL('chrome/nav.html', import.meta.url);

/**
 * The seven hand-maintained pages, site-relative.
 *
 * site/menu/{tiffin,lunch,dinner}/index.html are deliberately absent. They are
 * generated by tools/build-menu-pages.mjs, whose loadChrome() copies this very
 * block verbatim out of site/menu/index.html -- so syncing menu/index.html here
 * and then running `npm run build:menu` propagates to them. Writing them
 * directly would put two tools in charge of one file.
 */
export const PAGES = [
  'index.html',
  'about/index.html',
  'contact/index.html',
  'corporate/index.html',
  'services/index.html',
  'menu/index.html',
  '404.html',
];

/** Never written by this tool -- see the note on PAGES. Asserted below. */
export const GENERATED_PAGES = [
  'menu/tiffin/index.html',
  'menu/lunch/index.html',
  'menu/dinner/index.html',
];

for (const page of GENERATED_PAGES) {
  if (PAGES.includes(page)) {
    throw new Error(`${page} is generated by build-menu-pages.mjs and must not be in PAGES`);
  }
}

// The opening marker is written by this tool, not just matched by it, so its
// wording lives in one place and propagates on the next sync. It carries the
// instruction on purpose: someone opening the page to edit the nav needs to be
// told, right there, that the edit will be overwritten and what to do instead.
// A few hundred bytes of comment in the served HTML is the price of that, and
// it is worth paying.
export const START_MARKER =
  '<!-- sync:chrome start | shared topbar + nav, one copy in tools/chrome/nav.html. ' +
  'Do not edit this block here: edit that file, then run `npm run sync:chrome` in site/. -->';
export const END_MARKER = '<!-- sync:chrome end -->';

// Matched loosely so re-wording the opening marker does not orphan the pages.
const START_RE = /<!-- sync:chrome start[\s\S]*?-->/g;
const END_RE = /<!-- sync:chrome end -->/g;

// The nav links live in one container; aria-current is only ever applied inside
// it. Scoped rather than global because the brand logo is also an <a href="/">,
// and marking that one as the current page would be wrong on every page.
const NAV_LINKS_RE = /<div class="nav-links"[^>]*>[\s\S]*?<\/div>/;

/** Read the one copy of the block. Throws rather than writing anything empty. */
export function loadNav() {
  let nav;
  try {
    nav = readFileSync(NAV_SOURCE, 'utf8');
  } catch (err) {
    throw new Error(`cannot read the nav source at tools/chrome/nav.html: ${err.message}`);
  }
  nav = nav.replace(/\s+$/, '');
  if (!nav) throw new Error('tools/chrome/nav.html is empty');
  for (const [what, needle] of [
    ['the topbar', '<div class="topbar">'],
    ['a nav element', '<nav>'],
    ['a closing nav element', '</nav>'],
  ]) {
    if (!nav.includes(needle)) {
      throw new Error(`tools/chrome/nav.html has no ${what} (${needle}) -- refusing to sync`);
    }
  }
  if (!NAV_LINKS_RE.test(nav)) {
    throw new Error('tools/chrome/nav.html has no nav-links container -- refusing to sync');
  }
  if (nav.includes('aria-current')) {
    throw new Error(
      'tools/chrome/nav.html must not carry aria-current -- this tool adds it per page'
    );
  }
  return nav;
}

/**
 * The URL each page is served at, which is what aria-current is derived from.
 * null means "not a nav destination", so no link is marked.
 */
export function urlPathFor(page) {
  // 404.html is the error document, not a page anyone navigates to. Nothing in
  // the nav points at it and nothing should.
  if (page === '404.html') return null;
  return '/' + page.replace(/index\.html$/, '');
}

/** The block as it should appear on `page`, aria-current and all. */
export function navFor(page, nav = loadNav()) {
  const urlPath = urlPathFor(page);
  if (urlPath === null) return nav;

  const links = nav.match(NAV_LINKS_RE)[0];
  const open = `<a href="${urlPath}">`;
  const hits = links.split(open).length - 1;

  // Zero is legitimate and expected for /corporate/: it is reachable from the
  // footer only, appears in no page's primary nav, and so marks no link.
  if (hits === 0) return nav;
  if (hits > 1) {
    throw new Error(`the nav has ${hits} links to ${urlPath}; cannot tell which is the current page`);
  }
  const marked = links.replace(open, `<a href="${urlPath}" aria-current="page">`);
  return nav.replace(links, marked);
}

/** The exact text the markers should enclose on `page`, markers included. */
export function regionFor(page, nav = loadNav()) {
  return `${START_MARKER}\n${navFor(page, nav)}\n${END_MARKER}`;
}

/**
 * Locate the marked region in `html`. Throws on anything ambiguous: a page with
 * no markers, an opening marker with no close, or more than one of either. A
 * silent skip here is exactly the drift this tool exists to stop.
 */
export function findRegion(html, page) {
  const starts = html.match(START_RE) || [];
  const ends = html.match(END_RE) || [];
  if (starts.length === 0 && ends.length === 0) {
    throw new Error(
      `${page} has no sync:chrome markers. Wrap its topbar+nav in ${START_MARKER} and ${END_MARKER}, or drop it from PAGES.`
    );
  }
  if (starts.length !== 1) throw new Error(`${page} has ${starts.length} sync:chrome start markers, expected 1`);
  if (ends.length !== 1) throw new Error(`${page} has ${ends.length} sync:chrome end markers, expected 1`);

  const from = html.indexOf(starts[0]);
  const to = html.indexOf(ends[0]) + ends[0].length;
  if (to <= from) throw new Error(`${page} has its sync:chrome end marker before its start marker`);
  return { from, to, text: html.slice(from, to) };
}

/** Rewrite one page's region. Returns true when the file changed. */
export function syncPage(page, nav = loadNav()) {
  const file = new URL(page, SITE);
  const html = readFileSync(file, 'utf8');
  const { from, to, text } = findRegion(html, page);
  const wanted = regionFor(page, nav);
  if (text === wanted) return false;
  writeFileSync(file, html.slice(0, from) + wanted + html.slice(to), 'utf8');
  return true;
}

export function syncAll() {
  const nav = loadNav();
  const changed = [];
  for (const page of PAGES) {
    if (syncPage(page, nav)) changed.push(page);
  }
  return changed;
}

// Only run when invoked directly, so the test can import the module safely.
// process.argv[1] is undefined under `node -e`, so guard it.
const entry = typeof process.argv[1] === 'string' ? process.argv[1].replace(/\\/g, '/') : '';
if (entry.endsWith('sync-chrome.mjs')) {
  const changed = syncAll();
  for (const page of PAGES) {
    console.log(`  ${changed.includes(page) ? 'updated' : 'unchanged'}  site/${page}`);
  }
  console.log(
    changed.length
      ? `\n${changed.length} of ${PAGES.length} pages rewritten from tools/chrome/nav.html.`
      : `\nAll ${PAGES.length} pages already match tools/chrome/nav.html.`
  );
  console.log('Run `npm run build:menu` next if site/menu/index.html moved.');
}
