#!/usr/bin/env node
// Syncs the shared chrome -- topbar + nav, the site footer, and the shared runs
// of <head> -- into the hand-maintained pages.
//
//   npm run sync:chrome       (from site/)
//
// Between them the blocks were 7.6 KB duplicated by hand across seven pages, so
// a nav, footer or CSP change meant seven identical edits and any missed one
// drifted silently -- 404.html really did sit a Corporate link behind for a
// while. Each block now has one home under tools/chrome/, and this tool
// rewrites the marked region inside each page from it.
//
// This is deliberately NOT a static site generator. The pages stay whole,
// hand-editable HTML files under version control; only the regions between the
// markers are machine-owned. There is no layout file, no content extraction and
// no page-source directory, and there never should be: the output is committed
// like any other source file, because netlify.toml publishes site/ exactly as
// it stands and nothing is built at deploy time. See ADR-0004.
//
// Lives outside site/ deliberately -- site/ is the Netlify publish directory,
// so anything in it is served publicly. See ADR-0005.
//
// ORDERING: run this BEFORE `npm run build:menu`. The generated category pages
// copy their chrome verbatim out of site/menu/index.html, so building them from
// an unsynced hub bakes stale chrome into all three. `npm run build:menu`
// chains this script ahead of itself so the order cannot be got wrong by hand.

import { readFileSync, writeFileSync } from 'node:fs';

const SITE = new URL('../site/', import.meta.url);
const CHROME = new URL('chrome/', import.meta.url);

/**
 * The seven hand-maintained pages, site-relative.
 *
 * site/menu/{tiffin,lunch,dinner}/index.html are deliberately absent. They are
 * generated by tools/build-menu-pages.mjs, whose loadChrome() copies these very
 * blocks verbatim out of site/menu/index.html -- so syncing menu/index.html here
 * and then running `npm run build:menu` propagates to them. Writing them
 * directly would put two tools in charge of one file.
 */
export const PAGES = [
  'index.html',
  'about/index.html',
  'contact/index.html',
  'corporate/index.html',
  'services/index.html',
  'menu/index.html',
  '404.html',
];

/** Never written by this tool -- see the note on PAGES. Asserted below. */
export const GENERATED_PAGES = [
  'menu/tiffin/index.html',
  'menu/lunch/index.html',
  'menu/dinner/index.html',
  // The occasion pages slice the same sets by occasion tag rather than by
  // category (ADR-0007). They take their chrome from the same hub extraction,
  // so they carry the markers for the same reason the category pages do.
  'menu/housewarming/index.html',
  'menu/seemantham/index.html',
];

for (const page of GENERATED_PAGES) {
  if (PAGES.includes(page)) {
    throw new Error(`${page} is generated by build-menu-pages.mjs and must not be in PAGES`);
  }
}

// The opening marker is written by this tool, not just matched by it, so its
// wording lives in one place and propagates on the next sync. It carries the
// instruction on purpose: someone opening the page to edit the nav or the
// footer needs to be told, right there, that the edit will be overwritten and
// what to do instead. A few hundred bytes of comment in the served HTML is the
// price of that, and it is worth paying.
const startMarkerFor = r =>
  `<!-- ${r.marker} start | ${r.what}, one copy in tools/chrome/${r.sourceFile}. ` +
  'Do not edit this block here: edit that file, then run `npm run sync:chrome` in site/. -->';
const endMarkerFor = r => `<!-- ${r.marker} end -->`;

const escapeRe = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** The nav links live in one container; aria-current is only ever applied
 * inside it. Scoped rather than global because the brand logo is also an
 * <a href="/">, and marking that one as the current page would be wrong on
 * every page. */
const NAV_LINKS_RE = /<div class="nav-links"[^>]*>[\s\S]*?<\/div>/;

/**
 * The machine-owned regions. Adding one means an entry here plus its source
 * file, nothing else.
 *
 * `marker` is what makes two regions on one page tellable apart, and it is the
 * only asymmetry in this table: the nav was here first and its markers are
 * already committed in every page, so it keeps the unqualified `sync:chrome`
 * and every later region qualifies it (`sync:chrome footer`). Renaming the nav
 * markers for symmetry would rewrite ten pages to say the same thing. Note the
 * qualifier goes before `start`/`end`, not after: that keeps each region's
 * marker text a prefix no other region's can match, so the loose end of the
 * opening-marker pattern below cannot swallow a neighbour.
 *
 * `forPage` is where per-page variation lives. The nav derives aria-current
 * from the URL the page is served at; every other region so far has no per-page
 * variation at all -- the copies were byte-identical -- so it returns the
 * source unchanged. If a region ever needs a second parameter, that is a hint
 * the region boundary is drawn too wide.
 *
 * `pages` narrows a region to a subset of PAGES; omitted means all of them. It
 * exists because 404.html carries no Open Graph or Twitter tags -- an error
 * document needs no share card -- so those two regions genuinely do not exist
 * there. Scoping is not a weakening: a page inside a region's scope with no
 * markers is still an error, and so is a page outside it that has them.
 *
 * The three <head> regions are drawn only around runs that were already
 * contiguous and already byte-identical on every page in scope. Everything that
 * varies per page -- <title>, description, canonical, og:url, og:title,
 * og:description, twitter:title, twitter:description, prefetch, index.html's
 * keywords and fallback icon, and every JSON-LD block -- sits outside them, and
 * nothing was reordered to make a region bigger. In particular the CSP stays
 * exactly where it was, above every tag that loads a resource.
 */
export const REGIONS = [
  {
    name: 'nav',
    marker: 'sync:chrome',
    sourceFile: 'nav.html',
    what: 'shared topbar + nav',
    wraps: 'topbar+nav',
    requires: [
      ['the topbar', '<div class="topbar">'],
      ['a nav element', '<nav>'],
      ['a closing nav element', '</nav>'],
    ],
    check(src) {
      if (!NAV_LINKS_RE.test(src)) {
        throw new Error('tools/chrome/nav.html has no nav-links container -- refusing to sync');
      }
      if (src.includes('aria-current')) {
        throw new Error(
          'tools/chrome/nav.html must not carry aria-current -- this tool adds it per page'
        );
      }
    },
    forPage: (page, src) => navFor(page, src),
  },
  {
    name: 'footer',
    marker: 'sync:chrome footer',
    sourceFile: 'footer.html',
    what: 'shared site footer',
    wraps: 'footer',
    requires: [
      ['a footer element', '<footer>'],
      ['a closing footer element', '</footer>'],
    ],
    // No per-page variation, by design. The footer carries no aria-current:
    // its link list includes /corporate/, which is in no page's primary nav,
    // and marking the current page twice would be noise for a screen reader.
    forPage: (page, src) => src,
  },
  {
    name: 'head-csp',
    marker: 'sync:chrome head-csp',
    sourceFile: 'head-csp.html',
    what: 'shared CSP + referrer policy',
    wraps: 'CSP and referrer meta tags',
    // The highest-value region: it was the last copy-and-paste of the CSP
    // string, ten hand-maintained tags of it, which ADR-0008 named as the
    // remaining real duplication. The explanatory comment above the meta tag
    // was on index.html only; it is in the source now, so every page carries
    // it -- it is what tells a reader why a meta CSP exists alongside
    // site/_headers.
    //
    // The region must stay where it is: above the first tag that loads a
    // resource, since a CSP delivered after one has already started is not
    // applied to it. head-assets is the first such run and sits well below.
    requires: [
      ['a Content-Security-Policy meta tag', '<meta http-equiv="Content-Security-Policy"'],
      ['a referrer policy meta tag', '<meta name="referrer"'],
    ],
    forPage: (page, src) => src,
  },
  {
    name: 'head-assets',
    marker: 'sync:chrome head-assets',
    sourceFile: 'head-assets.html',
    what: 'shared font, stylesheet and analytics tags',
    wraps: 'preconnect, stylesheet and analytics tags',
    // The largest contiguous shared run in the head: both preconnects, the
    // Google Fonts stylesheet, /style.css, and the two halves of the GA4
    // snippet with the comment that explains why they are split (ADR-0009).
    requires: [
      ['a fonts preconnect', '<link rel="preconnect" href="https://fonts.googleapis.com">'],
      ['the site stylesheet', '<link rel="stylesheet" href="/style.css">'],
      ['the analytics config script', '<script src="/analytics.js" defer></script>'],
    ],
    forPage: (page, src) => src,
  },
  {
    name: 'head-social',
    marker: 'sync:chrome head-social',
    sourceFile: 'head-social.html',
    what: 'shared Open Graph card, locale and site name',
    wraps: 'og:image through twitter:card meta tags',
    // Six pages, not seven. 404.html carries no Open Graph or Twitter tags at
    // all and should not: an error document needs no share card. Its absence
    // there is deliberate, which is what `pages` records -- so the tool neither
    // adds them nor complains they are missing.
    //
    // The per-page half of the card -- og:url, og:title, og:description,
    // twitter:title, twitter:description -- sits outside this region on both
    // sides. What is here is only the parts that name the one shared card
    // image and the site itself.
    pages: PAGES.filter(p => p !== '404.html'),
    requires: [
      ['an Open Graph image', '<meta property="og:image"'],
      ['an Open Graph site name', '<meta property="og:site_name"'],
      ['a Twitter card type', '<meta name="twitter:card"'],
    ],
    forPage: (page, src) => src,
  },
  {
    name: 'head-twitter-image',
    marker: 'sync:chrome head-twitter-image',
    sourceFile: 'head-twitter-image.html',
    what: 'shared Twitter card image',
    wraps: 'twitter:image meta tags',
    // Two lines, and they cost more in markers than they hold in markup. They
    // are here anyway because they name the same og-card.jpg and repeat
    // og:image:alt word for word: replace the card and all four lines have to
    // move together. Guarding the og half and not this one would leave the
    // card half-covered, which reads as covered.
    //
    // Separate from head-social rather than folded into it because
    // twitter:title and twitter:description sit between the two runs and vary
    // per page. Merging them would mean reordering the head, which this tool
    // does not do.
    pages: PAGES.filter(p => p !== '404.html'),
    requires: [
      ['a Twitter card image', '<meta name="twitter:image"'],
      ['a Twitter card image description', '<meta name="twitter:image:alt"'],
    ],
    forPage: (page, src) => src,
  },
];

for (const r of REGIONS) {
  r.pages ??= PAGES;
  for (const page of r.pages) {
    if (!PAGES.includes(page)) {
      throw new Error(`region ${r.name} is scoped to ${page}, which is not in PAGES`);
    }
  }
  if (!r.pages.length) throw new Error(`region ${r.name} is scoped to no pages at all`);
  r.startMarker = startMarkerFor(r);
  r.endMarker = endMarkerFor(r);
  // The stable head of the opening marker: everything up to the region name.
  // build-menu-pages.mjs slices the generated pages' bottom chrome from here.
  r.startPrefix = `<!-- ${r.marker} start`;
  // Matched loosely after the prefix so re-wording the opening marker does not
  // orphan the pages.
  r.startRe = new RegExp(`${escapeRe(r.startPrefix)}[\\s\\S]*?-->`, 'g');
  r.endRe = new RegExp(escapeRe(r.endMarker), 'g');
}

/** The region descriptor by name. Throws rather than returning undefined. */
export function regionNamed(name) {
  const region = REGIONS.find(r => r.name === name);
  if (!region) throw new Error(`no such chrome region: ${name}`);
  return region;
}

/** Read the one copy of a region's block. Throws rather than writing anything empty. */
export function loadSource(region) {
  const path = `tools/chrome/${region.sourceFile}`;
  let src;
  try {
    src = readFileSync(new URL(region.sourceFile, CHROME), 'utf8');
  } catch (err) {
    throw new Error(`cannot read the ${region.name} source at ${path}: ${err.message}`);
  }
  src = src.replace(/\s+$/, '');
  if (!src) throw new Error(`${path} is empty`);
  for (const [what, needle] of region.requires) {
    if (!src.includes(needle)) {
      throw new Error(`${path} has no ${what} (${needle}) -- refusing to sync`);
    }
  }
  region.check?.(src);
  return src;
}

/** Every region's source, keyed by region name. */
export function loadSources() {
  return Object.fromEntries(REGIONS.map(r => [r.name, loadSource(r)]));
}

/**
 * The URL each page is served at, which is what aria-current is derived from.
 * null means "not a nav destination", so no link is marked.
 */
export function urlPathFor(page) {
  // 404.html is the error document, not a page anyone navigates to. Nothing in
  // the nav points at it and nothing should.
  if (page === '404.html') return null;
  return '/' + page.replace(/index\.html$/, '');
}

/** The nav block as it should appear on `page`, aria-current and all. */
export function navFor(page, nav = loadSource(regionNamed('nav'))) {
  const urlPath = urlPathFor(page);
  if (urlPath === null) return nav;

  const links = nav.match(NAV_LINKS_RE)[0];
  const open = `<a href="${urlPath}">`;
  const hits = links.split(open).length - 1;

  // Zero is legitimate and expected for /corporate/: it is reachable from the
  // footer only, appears in no page's primary nav, and so marks no link.
  if (hits === 0) return nav;
  if (hits > 1) {
    throw new Error(`the nav has ${hits} links to ${urlPath}; cannot tell which is the current page`);
  }
  const marked = links.replace(open, `<a href="${urlPath}" aria-current="page">`);
  return nav.replace(links, marked);
}

/** The exact text `region`'s markers should enclose on `page`, markers included. */
export function regionFor(region, page, src = loadSource(region)) {
  return `${region.startMarker}\n${region.forPage(page, src)}\n${region.endMarker}`;
}

/**
 * Locate one marked region in `html`. Throws on anything ambiguous: a page with
 * no markers, an opening marker with no close, or more than one of either. A
 * silent skip here is exactly the drift this tool exists to stop.
 */
export function findRegion(region, html, page) {
  const starts = html.match(region.startRe) || [];
  const ends = html.match(region.endRe) || [];
  if (starts.length === 0 && ends.length === 0) {
    throw new Error(
      `${page} has no ${region.marker} markers. Wrap its ${region.wraps} in ${region.startMarker} and ${region.endMarker}, or drop it from PAGES.`
    );
  }
  if (starts.length !== 1) {
    throw new Error(`${page} has ${starts.length} ${region.marker} start markers, expected 1`);
  }
  if (ends.length !== 1) {
    throw new Error(`${page} has ${ends.length} ${region.marker} end markers, expected 1`);
  }

  const from = html.indexOf(starts[0]);
  const to = html.indexOf(ends[0]) + ends[0].length;
  if (to <= from) {
    throw new Error(`${page} has its ${region.marker} end marker before its start marker`);
  }
  return { from, to, text: html.slice(from, to) };
}

/**
 * The regions that apply to `page`, in table order.
 *
 * The inverse of a region's `pages`. A region out of scope on a page is not
 * written there -- and, checked in syncPage, must not be marked there either:
 * markers this tool will never rewrite are exactly the stale block the sync
 * exists to prevent.
 */
export function regionsFor(page) {
  return REGIONS.filter(r => r.pages.includes(page));
}

/**
 * Rewrite one page's regions. Returns the names of the regions that moved.
 *
 * Each region is located against the text as it stands after the previous
 * rewrite, so the offsets are never stale and the table need not be in document
 * order.
 */
export function syncPage(page, sources = loadSources()) {
  const file = new URL(page, SITE);
  let html = readFileSync(file, 'utf8');
  const moved = [];
  for (const region of REGIONS) {
    if (!region.pages.includes(page)) {
      // Out of scope. Silence here would be fine, but a marker that is never
      // rewritten would not be: it would look owned and be frozen. Refuse it.
      // .match, not .test: startRe and endRe are global, so .test would carry
      // lastIndex from one page to the next and start missing matches.
      if (html.match(region.startRe) || html.match(region.endRe)) {
        throw new Error(
          `${page} carries ${region.marker} markers but is outside that region's scope. Remove them, or add ${page} to the region's pages in tools/sync-chrome.mjs.`
        );
      }
      continue;
    }
    const { from, to, text } = findRegion(region, html, page);
    const wanted = regionFor(region, page, sources[region.name]);
    if (text === wanted) continue;
    html = html.slice(0, from) + wanted + html.slice(to);
    moved.push(region.name);
  }
  if (moved.length) writeFileSync(file, html, 'utf8');
  return moved;
}

/** Every page's regions. Returns a page -> moved-region-names map of what changed. */
export function syncAll() {
  const sources = loadSources();
  const changed = {};
  for (const page of PAGES) {
    const moved = syncPage(page, sources);
    if (moved.length) changed[page] = moved;
  }
  return changed;
}

// Only run when invoked directly, so the test can import the module safely.
// process.argv[1] is undefined under `node -e`, so guard it.
const entry = typeof process.argv[1] === 'string' ? process.argv[1].replace(/\\/g, '/') : '';
if (entry.endsWith('sync-chrome.mjs')) {
  const changed = syncAll();
  for (const page of PAGES) {
    const moved = changed[page];
    console.log(`  ${moved ? `updated (${moved.join(', ')})` : 'unchanged'}  site/${page}`);
  }
  const n = Object.keys(changed).length;
  const from = `the ${REGIONS.length} sources in tools/chrome/`;
  console.log(
    n
      ? `\n${n} of ${PAGES.length} pages rewritten from ${from}.`
      : `\nAll ${PAGES.length} pages already match ${from}.`
  );
  console.log('Run `npm run build:menu` next if site/menu/index.html moved.');
}
