#!/usr/bin/env node
// Syncs the shared chrome -- topbar + nav, and the site footer -- into the
// hand-maintained pages.
//
//   npm run sync:chrome       (from site/)
//
// Between them the two blocks were 4.7 KB duplicated by hand across seven
// pages, so a nav or footer change meant seven identical edits and any missed
// one drifted silently -- 404.html really did sit a Corporate link behind for a
// while. Each block now has one home under tools/chrome/, and this tool
// rewrites the marked region inside each page from it.
//
// This is deliberately NOT a static site generator. The pages stay whole,
// hand-editable HTML files under version control; only the regions between the
// markers are machine-owned. There is no layout file, no content extraction and
// no page-source directory, and there never should be: the output is committed
// like any other source file, because netlify.toml publishes site/ exactly as
// it stands and nothing is built at deploy time. See ADR-0004.
//
// Lives outside site/ deliberately -- site/ is the Netlify publish directory,
// so anything in it is served publicly. See ADR-0005.
//
// ORDERING: run this BEFORE `npm run build:menu`. The generated category pages
// copy their chrome verbatim out of site/menu/index.html, so building them from
// an unsynced hub bakes stale chrome into all three. `npm run build:menu`
// chains this script ahead of itself so the order cannot be got wrong by hand.

import { readFileSync, writeFileSync } from 'node:fs';

const SITE = new URL('../site/', import.meta.url);
const CHROME = new URL('chrome/', import.meta.url);

/**
 * The seven hand-maintained pages, site-relative.
 *
 * site/menu/{tiffin,lunch,dinner}/index.html are deliberately absent. They are
 * generated by tools/build-menu-pages.mjs, whose loadChrome() copies these very
 * blocks verbatim out of site/menu/index.html -- so syncing menu/index.html here
 * and then running `npm run build:menu` propagates to them. Writing them
 * directly would put two tools in charge of one file.
 */
export const PAGES = [
  'index.html',
  'about/index.html',
  'contact/index.html',
  'corporate/index.html',
  'services/index.html',
  'menu/index.html',
  '404.html',
];

/** Never written by this tool -- see the note on PAGES. Asserted below. */
export const GENERATED_PAGES = [
  'menu/tiffin/index.html',
  'menu/lunch/index.html',
  'menu/dinner/index.html',
];

for (const page of GENERATED_PAGES) {
  if (PAGES.includes(page)) {
    throw new Error(`${page} is generated by build-menu-pages.mjs and must not be in PAGES`);
  }
}

// The opening marker is written by this tool, not just matched by it, so its
// wording lives in one place and propagates on the next sync. It carries the
// instruction on purpose: someone opening the page to edit the nav or the
// footer needs to be told, right there, that the edit will be overwritten and
// what to do instead. A few hundred bytes of comment in the served HTML is the
// price of that, and it is worth paying.
const startMarkerFor = r =>
  `<!-- ${r.marker} start | ${r.what}, one copy in tools/chrome/${r.sourceFile}. ` +
  'Do not edit this block here: edit that file, then run `npm run sync:chrome` in site/. -->';
const endMarkerFor = r => `<!-- ${r.marker} end -->`;

const escapeRe = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** The nav links live in one container; aria-current is only ever applied
 * inside it. Scoped rather than global because the brand logo is also an
 * <a href="/">, and marking that one as the current page would be wrong on
 * every page. */
const NAV_LINKS_RE = /<div class="nav-links"[^>]*>[\s\S]*?<\/div>/;

/**
 * The machine-owned regions. Adding a third -- the CSP is the obvious
 * candidate -- means one more entry here plus its source file, nothing else.
 *
 * `marker` is what makes two regions on one page tellable apart, and it is the
 * only asymmetry in this table: the nav was here first and its markers are
 * already committed in every page, so it keeps the unqualified `sync:chrome`
 * and every later region qualifies it (`sync:chrome footer`). Renaming the nav
 * markers for symmetry would rewrite ten pages to say the same thing. Note the
 * qualifier goes before `start`/`end`, not after: that keeps each region's
 * marker text a prefix no other region's can match, so the loose end of the
 * opening-marker pattern below cannot swallow a neighbour.
 *
 * `forPage` is where per-page variation lives. The nav derives aria-current
 * from the URL the page is served at; the footer has no per-page variation at
 * all -- the seven copies were byte-identical -- so it returns the source
 * unchanged. If a region ever needs a second parameter, that is a hint the
 * region boundary is drawn too wide.
 */
export const REGIONS = [
  {
    name: 'nav',
    marker: 'sync:chrome',
    sourceFile: 'nav.html',
    what: 'shared topbar + nav',
    wraps: 'topbar+nav',
    requires: [
      ['the topbar', '<div class="topbar">'],
      ['a nav element', '<nav>'],
      ['a closing nav element', '</nav>'],
    ],
    check(src) {
      if (!NAV_LINKS_RE.test(src)) {
        throw new Error('tools/chrome/nav.html has no nav-links container -- refusing to sync');
      }
      if (src.includes('aria-current')) {
        throw new Error(
          'tools/chrome/nav.html must not carry aria-current -- this tool adds it per page'
        );
      }
    },
    forPage: (page, src) => navFor(page, src),
  },
  {
    name: 'footer',
    marker: 'sync:chrome footer',
    sourceFile: 'footer.html',
    what: 'shared site footer',
    wraps: 'footer',
    requires: [
      ['a footer element', '<footer>'],
      ['a closing footer element', '</footer>'],
    ],
    // No per-page variation, by design. The footer carries no aria-current:
    // its link list includes /corporate/, which is in no page's primary nav,
    // and marking the current page twice would be noise for a screen reader.
    forPage: (page, src) => src,
  },
];

for (const r of REGIONS) {
  r.startMarker = startMarkerFor(r);
  r.endMarker = endMarkerFor(r);
  // The stable head of the opening marker: everything up to the region name.
  // build-menu-pages.mjs slices the generated pages' bottom chrome from here.
  r.startPrefix = `<!-- ${r.marker} start`;
  // Matched loosely after the prefix so re-wording the opening marker does not
  // orphan the pages.
  r.startRe = new RegExp(`${escapeRe(r.startPrefix)}[\\s\\S]*?-->`, 'g');
  r.endRe = new RegExp(escapeRe(r.endMarker), 'g');
}

/** The region descriptor by name. Throws rather than returning undefined. */
export function regionNamed(name) {
  const region = REGIONS.find(r => r.name === name);
  if (!region) throw new Error(`no such chrome region: ${name}`);
  return region;
}

/** Read the one copy of a region's block. Throws rather than writing anything empty. */
export function loadSource(region) {
  const path = `tools/chrome/${region.sourceFile}`;
  let src;
  try {
    src = readFileSync(new URL(region.sourceFile, CHROME), 'utf8');
  } catch (err) {
    throw new Error(`cannot read the ${region.name} source at ${path}: ${err.message}`);
  }
  src = src.replace(/\s+$/, '');
  if (!src) throw new Error(`${path} is empty`);
  for (const [what, needle] of region.requires) {
    if (!src.includes(needle)) {
      throw new Error(`${path} has no ${what} (${needle}) -- refusing to sync`);
    }
  }
  region.check?.(src);
  return src;
}

/** Every region's source, keyed by region name. */
export function loadSources() {
  return Object.fromEntries(REGIONS.map(r => [r.name, loadSource(r)]));
}

/**
 * The URL each page is served at, which is what aria-current is derived from.
 * null means "not a nav destination", so no link is marked.
 */
export function urlPathFor(page) {
  // 404.html is the error document, not a page anyone navigates to. Nothing in
  // the nav points at it and nothing should.
  if (page === '404.html') return null;
  return '/' + page.replace(/index\.html$/, '');
}

/** The nav block as it should appear on `page`, aria-current and all. */
export function navFor(page, nav = loadSource(regionNamed('nav'))) {
  const urlPath = urlPathFor(page);
  if (urlPath === null) return nav;

  const links = nav.match(NAV_LINKS_RE)[0];
  const open = `<a href="${urlPath}">`;
  const hits = links.split(open).length - 1;

  // Zero is legitimate and expected for /corporate/: it is reachable from the
  // footer only, appears in no page's primary nav, and so marks no link.
  if (hits === 0) return nav;
  if (hits > 1) {
    throw new Error(`the nav has ${hits} links to ${urlPath}; cannot tell which is the current page`);
  }
  const marked = links.replace(open, `<a href="${urlPath}" aria-current="page">`);
  return nav.replace(links, marked);
}

/** The exact text `region`'s markers should enclose on `page`, markers included. */
export function regionFor(region, page, src = loadSource(region)) {
  return `${region.startMarker}\n${region.forPage(page, src)}\n${region.endMarker}`;
}

/**
 * Locate one marked region in `html`. Throws on anything ambiguous: a page with
 * no markers, an opening marker with no close, or more than one of either. A
 * silent skip here is exactly the drift this tool exists to stop.
 */
export function findRegion(region, html, page) {
  const starts = html.match(region.startRe) || [];
  const ends = html.match(region.endRe) || [];
  if (starts.length === 0 && ends.length === 0) {
    throw new Error(
      `${page} has no ${region.marker} markers. Wrap its ${region.wraps} in ${region.startMarker} and ${region.endMarker}, or drop it from PAGES.`
    );
  }
  if (starts.length !== 1) {
    throw new Error(`${page} has ${starts.length} ${region.marker} start markers, expected 1`);
  }
  if (ends.length !== 1) {
    throw new Error(`${page} has ${ends.length} ${region.marker} end markers, expected 1`);
  }

  const from = html.indexOf(starts[0]);
  const to = html.indexOf(ends[0]) + ends[0].length;
  if (to <= from) {
    throw new Error(`${page} has its ${region.marker} end marker before its start marker`);
  }
  return { from, to, text: html.slice(from, to) };
}

/**
 * Rewrite one page's regions. Returns the names of the regions that moved.
 *
 * Each region is located against the text as it stands after the previous
 * rewrite, so the offsets are never stale and the table need not be in document
 * order.
 */
export function syncPage(page, sources = loadSources()) {
  const file = new URL(page, SITE);
  let html = readFileSync(file, 'utf8');
  const moved = [];
  for (const region of REGIONS) {
    const { from, to, text } = findRegion(region, html, page);
    const wanted = regionFor(region, page, sources[region.name]);
    if (text === wanted) continue;
    html = html.slice(0, from) + wanted + html.slice(to);
    moved.push(region.name);
  }
  if (moved.length) writeFileSync(file, html, 'utf8');
  return moved;
}

/** Every page's regions. Returns a page -> moved-region-names map of what changed. */
export function syncAll() {
  const sources = loadSources();
  const changed = {};
  for (const page of PAGES) {
    const moved = syncPage(page, sources);
    if (moved.length) changed[page] = moved;
  }
  return changed;
}

// Only run when invoked directly, so the test can import the module safely.
// process.argv[1] is undefined under `node -e`, so guard it.
const entry = typeof process.argv[1] === 'string' ? process.argv[1].replace(/\\/g, '/') : '';
if (entry.endsWith('sync-chrome.mjs')) {
  const changed = syncAll();
  for (const page of PAGES) {
    const moved = changed[page];
    console.log(`  ${moved ? `updated (${moved.join(', ')})` : 'unchanged'}  site/${page}`);
  }
  const n = Object.keys(changed).length;
  const from = REGIONS.map(r => `tools/chrome/${r.sourceFile}`).join(' and ');
  console.log(
    n
      ? `\n${n} of ${PAGES.length} pages rewritten from ${from}.`
      : `\nAll ${PAGES.length} pages already match ${from}.`
  );
  console.log('Run `npm run build:menu` next if site/menu/index.html moved.');
}
